version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      cosmjs:
        patterns:
          - "@cosmjs/*"
          - "cosmjs-types"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
